### ISSUE TITLE
Qos 

### ISSUE THREAD

**Issue by SunGod1202** [TommasoVandermeer/Hospitalbot-Path-Planning#1]
I have a question. How should I handle the following issue? I am using ROS2 Foxy, not Humble.

New publisher discovered on topic '/demo/laser/out', offering incompatible QoS. No messages will be received from it. Last incompatible policy: RELIABILITY

**Comment by TommasoVandermeer** [comment]
Hi, it seems like the publisher used to publish laser data has a different and incompatible QoS profile with respect to the subscriber to /demo/laser/out. 

You can try to change the QoS profile of that subscriber in the robot_controller.py file and see if you find a compatible QoS profile.

You can check Qos compatibilities for ROS Foxy [here](https://docs.ros.org/en/foxy/Concepts/About-Quality-of-Service-Settings.html).

**Comment by SunGod1202** [comment]
I will try the suggestions you provided and will reply to you after experimenting. Thank you.

**Comment by SunGod1202** [comment]
I have resolved this issue by handling it this way. Thank you for your assistance.

self.subscription = self.create_subscription(
Odometry,
'/odom',
self.listener_callback,
rclpy.qos.qos_profile_sensor_data)
